### ISSUE TITLE
Could you add Pow()?

### ISSUE THREAD

**Issue by infmon** [asik/FixedMath.Net#10]
First off, thank you so much for this library.  It's the only one that I've found that I've gotten working for my application.

The one thing that it's missing that I really need is to be able to calculate fractional powers, the same as Mathf.Pow() does.  I've found at least one library that seems to do it in 32bit (https://github.com/jpernst/FixedPointy/blob/master/FixMath.cs) but I lack the mathematical/bit manipulation skill to add it to your library.  I think the place where I get tripped up in the FixedPointy implementation is it uses long to get enough space when calculating Pow(), so I'm not sure what to do to add it to your library.

**Comment by asik** [comment]
Hey, just to say I noticed your request, unfortunately I don't know how to implement this any more than you do. I'd welcome a pull request for it.

**Comment by sam-vdp** [comment]
A bit late to the party, but I recently added that. Please see PR #12

**Comment by asik** [comment]
Added in https://github.com/asik/FixedMath.Net/commit/6dff4372339fca951f8042e6382afcc04d1c1995
