### ISSUE TITLE
Is this library correct in terms of Base10 calculations?

### ISSUE THREAD

**Issue by joeventura** [asik/FixedMath.Net#14]
I am exploring to use this library in a financial application where base 10 calculations must be correct within 10 decimal paces.

System.Decimal provides correct base 10 math within its precision range, I believe 28 decimal places.

This library is very exciting because many applications can benefit from a faster, yet correct numeric data type.

How does this library compare to System.Decimal in terms of correctness?

**Comment by asik** [comment]
The precision of this type is 2^-32, which is approx 2,3283e-10. So it's not quite 10 decimals of accuracy.
Basic arithmetic (+, -, *, /, %) is all correct within the precision of the type and well-tested.
Other operations have various degrees of accuracy which are usually noted in the description.

That said, I would not recommend using this as a faster replacement of System.Decimal (assuming it's faster...). This type is intended to replace System.Single or System.Double in applications where determinism is important or floating-point hardware is not available.
