### ISSUE TITLE
ReflectionTypeLoadException: The classes in the module cannot be loaded.

### ISSUE THREAD

**Issue by ubanck** [asik/FixedMath.Net#15]
Sorry,excuse me!
When I use reflection,it will show the error!    For I test, the file "Fix64SinLut" and "Fix64TanLut" is so large!
I use it for moba game by Unity!
how can I solve this problem

**Comment by asik** [comment]
Sounds like you're compiling for the wrong .NET framework version. Make sure it's compatible with whatever Unity supports. Anyway if you need help with programming questions please use StackOverflow.

**Comment by ubanck** [comment]
OK,Thank you! I get it
