### ISSUE TITLE
Is changing "Fractional_Places" supported?

### ISSUE THREAD

**Issue by Bamboy** [asik/FixedMath.Net#20]
For my project, I would much prefer to have more integer places than decimal places. (I'm thinking maybe 5 or 8 decimal places)

If I change "**const int FRACTIONAL_PLACES = 32;**" to a lower value will everything still work correctly? Or do more changes need to be made or is it just plain unsupported?

Also, I'll probably be making a few extensions for this, like Vector2 or Vector3. They probably won't be that in depth, but would you be interested in something like this?

It's been hard to find any good libraries out there, and I'm not so great at the heavy math stuff, so thank you for your efforts! :)

**Comment by asik** [comment]
It's not supported. You could try it and see what breaks. I expect simple things like arithmetic would keep working, so if that's all you need maybe you can work with that.
If people want to build things like Vector or Matrix types based on this, that's great, but I wouldn't integrate it in the library.

**Comment by Bamboy** [comment]
Okay, I'll just work with what's there then. Thank you for answering!
