### ISSUE TITLE
Determinism

### ISSUE THREAD

**Issue by mcintyre321** [asik/FixedMath.Net#4]
Is this library deterministic across processor architectures (aside from perhaps the floating point conversions)?

**Comment by asik** [comment]
Yes it is entirely determistic, including floating point conversions.

**Comment by mcintyre321** [comment]
Awesome!

I'm planning on running a model on a server under c# and cross compiled to JS on the client (via JSIL), so thats great to hear.

**Comment by asik** [comment]
Cool, let me know if you have any issues with it.
